### ISSUE TITLE
shakemapprocessor.h missing

### ISSUE THREAD

**Issue by gempa-jabe** [ovsm-dev/ipgp-addons#3]
```
src/ipgp-addons/libs/ipgp/gui/datamodel/shakemapscity/shakemapscitywidget.h:33:52: fatal error: seiscomp3/processing/shakemapprocessor.h: No such file or directory
```

You probably modified the SC3 code and that change is not upstream. Either issue a PR to review and incorporate your changes into SC3 or move shakemapeprocessor.h to ipgp-addons otherwise the package will not compile.

**Comment by ovsm-dev** [comment]
I think we moved this file and perhaps didn't changed all the directions in the code or we forgot it.
Stephen will have a look.

In the meantime, I've de-activated the shakemapscity widget compilation that uses this library.

**Comment by gempa-jabe** [comment]
OK, I can confirm that is compiles now.
